#!/bin/sh

today=$(date '+%Y-%m-%d')
count=$(eval "ls -la ~/Desktop | grep Screen\ Shot | wc -l | tr -d '[:space:]'")
dir="screenshots_$today"
if [ $count == 0 ]; then
  echo No screenshots at: ~/Desktop
  exit
fi
if [ ! -d ~/Desktop/$dir ]; then
  echo Making new folder at: ~/Desktop/$dir
  mkdir ~/Desktop/$dir
fi
echo Moving $count screenshots into ~/Desktop/$dir
eval "mv ~/Desktop/Screen\ Shot* ~/Desktop/$dir"
